#!/bin/bash

echo -e "Updating..."
sudo apt-get update 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when updating." >&2
  exit 1
fi

echo -e "Installing RVM..."
\curl -sSL https://get.rvm.io | bash 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing RVM." >&2
  exit 1
fi

# need to reload to use rvm
rvm reload

echo -e "Installing ruby 2.4.1..."
rvm install 2.4.1 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing ruby 2.4.1." >&2
  exit 1
fi

rvm use 2.4.1 --default

echo -e "Cofiguring RVM..."
rvm gemset create rails5.1 --default 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Cannot create RVM gemset!" >&2
  exit 1
fi

rvm use 2.4.1@rails5.1

echo -e "Installing rails 5.1..."
gem install rails -v 5.1 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing rails 5.1." >&2
  exit 1
fi

echo -e "Installing yarn..."
npm install --global yarn

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing yarn." >&2
  exit 1
fi

echo -e "Clear commad files"
rm -rf alpaca-command

echo -e "Finish environment settings! Have fun coding!"
