#!/bin/bash

echo -e "Alpaca says: Updating system..."
sudo apt-get update 1> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when updating."
  exit 1
fi

echo -e "Alpaca says: Installing RVM..."
\curl -sSL https://get.rvm.io | bash 12> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing RVM." >&2
  exit 1
fi

# need to reload to use rvm
rvm reload > /dev/null

echo -e "Alpaca says: Installing ruby 2.4.1"
rvm install 2.4.1 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing ruby 2.4.1." >&2
  exit 1
fi

# need to include script first
source /usr/local/rvm/scripts/rvm

rvm use 2.4.1 --default > /dev/null

rvm gemset create rails5.1 --default > /dev/null

rvm use 2.4.1@rails5.1 --default > /dev/null

echo -e "Alpaca says: Installing rails 5.1.0"
gem install rails -v 5.1 2> /dev/null

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing rails 5.1." >&2
  exit 1
fi

echo -e "Alpaca says: Installing yarn..."
npm install --global yarn

if [ $? -ne 0 ]
then
  echo "Something went wrong when installing yarn." >&2
  exit 1
fi

echo -e "Clear command files"
rm -rf alpaca-command

echo -e "Success! Have fun coding!"
